project:
  type: website

website:
  title: "Reportes Test"
  navbar:
    left:
      - text: "Sobre este sitio"
        href: index.qmd # siempre debe tener este archivo
  sidebar:
    style: docked
    contents:
      - index.qmd
      - section: "1er reporte"
        contents:
          - mis_reportes/reporte-01.qmd
      - section: "2do reporte"
        contents:
          - mis_reportes/reporte-02.qmd
      - section: "3er reporte"
        contents:
          - mis_reportes/reporte-03.qmd
       - section: "4to reporte"
        contents:
          - mis_reportes/reporte-04.qmd

format:
  html:
    theme: superhero
    toc: true
    lang: es
